name:                bomberman-client
version:             0.1.0.0
github:              "githubuser/bomberman-client"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bomberman-client#readme>

dependencies:
- base >= 4.7 && < 5
- uuid
- random
- stm
- bytestring

library:
  source-dirs: src

executables:
  bomberman-client-1:
    main:                Main.hs
    source-dirs:         app1
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bomberman-client
    - wreq
    - aeson
    - lens
    - ansi-terminal
    - string-conversions
    
  bomberman-client-2:
    main:                Main.hs
    source-dirs:         app2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bomberman-client
    - wreq
    - aeson
    - lens
    - ansi-terminal
    - string-conversions

  bomberman-server-client:
    main:                Main.hs
    source-dirs:         app4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bomberman-client
    - bytestring
    - wreq
    - lens
    - ansi-terminal
    - string-conversions
    - scotty
    - containers
    - http-types
    - uuid
    - random
    - stm
    - base64-bytestring
    - text


  bomberman-client:
    main:                Main.hs
    source-dirs:         app3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bomberman-client
    - bytestring
    - wreq
    - lens
    - ansi-terminal
    - string-conversions


tests:
  bomberman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bomberman-client
