resolver: lts-18.0
compiler: ghc-8.10.5
compiler-check: match-exact

# Local packages, usually specified by relative directory name
packages:
- '.'

extra-deps:
  - regex-posix-clib-2.7

flags:
  regex-posix:
    _regex-posix-clib: true
